# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/ASUS/OneDrive/Documents/DSC/DSC.srcs/sources_1/ip/floating_point_3/floating_point_3.xci
# IP: The module: 'floating_point_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ASUS/OneDrive/Documents/DSC/DSC.gen/sources_1/ip/floating_point_3/floating_point_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'floating_point_3'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/ASUS/OneDrive/Documents/DSC/DSC.srcs/sources_1/ip/floating_point_3/floating_point_3.xci
# IP: The module: 'floating_point_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ASUS/OneDrive/Documents/DSC/DSC.gen/sources_1/ip/floating_point_3/floating_point_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'floating_point_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
