# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/ASUS/OneDrive/Documents/DSC/DSC.runs/synth_1/assymetry_calc.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param general.usePosixSpawnForFork 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a200tfbg484-2L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/ASUS/OneDrive/Documents/DSC/DSC.cache/wt [current_project]
set_property parent.project_path C:/Users/ASUS/OneDrive/Documents/DSC/DSC.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/ASUS/OneDrive/Documents/DSC/DSC.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib {
  C:/Users/ASUS/OneDrive/Documents/DSC/DSC.srcs/sources_1/new/fix_to_float.v
  C:/Users/ASUS/OneDrive/Documents/DSC/DSC.srcs/sources_1/new/float_sub.v
  C:/Users/ASUS/OneDrive/Documents/DSC/DSC.srcs/sources_1/new/fp_absolute.v
  C:/Users/ASUS/OneDrive/Documents/DSC/DSC.srcs/sources_1/new/fp_div.v
  C:/Users/ASUS/OneDrive/Documents/DSC/DSC.srcs/sources_1/new/assymetry_calc.v
}
read_ip -quiet C:/Users/ASUS/OneDrive/Documents/DSC/DSC.srcs/sources_1/ip/floating_point_0/floating_point_0.xci
set_property used_in_implementation false [get_files -all c:/Users/ASUS/OneDrive/Documents/DSC/DSC.gen/sources_1/ip/floating_point_0/floating_point_0_ooc.xdc]

read_ip -quiet C:/Users/ASUS/OneDrive/Documents/DSC/DSC.srcs/sources_1/ip/floating_point_1/floating_point_1.xci
set_property used_in_implementation false [get_files -all c:/Users/ASUS/OneDrive/Documents/DSC/DSC.gen/sources_1/ip/floating_point_1/floating_point_1_ooc.xdc]

read_ip -quiet C:/Users/ASUS/OneDrive/Documents/DSC/DSC.srcs/sources_1/ip/floating_point_2/floating_point_2.xci

read_ip -quiet C:/Users/ASUS/OneDrive/Documents/DSC/DSC.srcs/sources_1/ip/floating_point_3/floating_point_3.xci
set_property used_in_implementation false [get_files -all c:/Users/ASUS/OneDrive/Documents/DSC/DSC.gen/sources_1/ip/floating_point_3/floating_point_3_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental C:/Users/ASUS/OneDrive/Documents/DSC/DSC.srcs/utils_1/imports/synth_1/assymetry_calc.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top assymetry_calc -part xc7a200tfbg484-2L
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef assymetry_calc.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file assymetry_calc_utilization_synth.rpt -pb assymetry_calc_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
